version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stats-api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/stats_db
    depends_on:
      - db
  
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stats_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
  